-- Safely add session_id to projects if it doesn't exist
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='session_id') THEN
    ALTER TABLE public.projects ADD COLUMN session_id text;
    -- Set a default for existing rows if any
    UPDATE public.projects SET session_id = 'default' WHERE session_id IS NULL;
    ALTER TABLE public.projects ALTER COLUMN session_id SET NOT NULL;
  END IF;
END $$;

-- Create the projects table if it doesn't exist (fallback/initial)
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  session_id text not null,
  name text not null,
  content text not null,
  language text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Add unique constraint to prevent duplicate files in the same session
DO $$ 
BEGIN 
  -- First, clean up any existing duplicates by keeping only the most recent one
  DELETE FROM public.projects a
  USING public.projects b
  WHERE a.id < b.id 
    AND a.session_id = b.session_id 
    AND a.name = b.name;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_session_id_name_key') THEN
    ALTER TABLE public.projects ADD CONSTRAINT projects_session_id_name_key UNIQUE (session_id, name);
  END IF;
END $$;

-- Create policies safely
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable read access for all users') THEN
    CREATE POLICY "Enable read access for all users" ON public.projects FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable insert access for all users') THEN
    CREATE POLICY "Enable insert access for all users" ON public.projects FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable delete access for all users') THEN
    CREATE POLICY "Enable delete access for all users" ON public.projects FOR DELETE USING (true);
  END IF;

  -- Add update policy
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable update access for all users') THEN
    CREATE POLICY "Enable update access for all users" ON public.projects FOR UPDATE USING (true);
  END IF;
END $$;
