import { Octokit } from "@octokit/rest";

// Helper for browser-compatible Base64 encoding (UTF-8 safe)
function toBase64(str: string) {
  return btoa(unescape(encodeURIComponent(str)));
}

// Helper for browser-compatible Base64 decoding (UTF-8 safe)
function fromBase64(str: string) {
  return decodeURIComponent(escape(atob(str)));
}

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export async function verifyAndSetupGithub(pat: string) {
  const octokit = new Octokit({ auth: pat });
  // Just verify the user exists
  const { data: user } = await octokit.users.getAuthenticated();
  return { user };
}

export async function uploadProjectToGithub(
  pat: string,
  repoName: string,
  files: { name: string; content: string }[],
  envVars: Record<string, string>
) {
  const octokit = new Octokit({ auth: pat });
  const { data: user } = await octokit.users.getAuthenticated();

  // 1. Create or Get Repo
  try {
    await octokit.repos.get({ owner: user.login, repo: repoName });
  } catch (e: any) {
    if (e.status === 404) {
      await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        private: true,
        description: "Generated by ForeverMore.Ai",
      });
      // Wait a bit for repo to be ready
      await delay(2000);
    } else {
      throw e;
    }
  }

  // 2. Prepare content
  // README
  const readme = `# ForeverMore.Ai

![Logo](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7uLSVF9mN-H-wlSvbS_ARTnH7-Y490s_jvYEVVzls4w&s=10)

You Can Edit Your Project On 
https://forevermorev1.vercel.app/

This Is A Multi Ai Agent Tool. It is designed to help developers and creators build, deploy, and manage AI-powered applications with ease. 

### Features:
- **Multi-Agent Collaboration**: Orchestrate multiple AI agents to work together on complex tasks.
- **Real-Time Code Generation**: Watch as the AI writes and refines code in real-time.
- **Instant Preview**: See your changes immediately with the built-in web preview engine.
- **GitHub Integration**: Seamlessly sync your projects and history to GitHub.
- **Custom Personas**: Create and deploy custom AI models with unique personalities and instructions.
- **Community Hub**: Share and discover chatbots created by the community.
- **Secure & Private**: Your data is handled with care, and you have full control over your API keys and project files.

Start building your dream AI application today with ForeverMore.Ai!
`;

  // .env
  const envContent = Object.entries(envVars)
    .map(([k, v]) => `${k}=${v}`)
    .join('\n');

  // Combine files
  const filesToUpload = [
    ...files,
    { name: 'README.md', content: readme },
    { name: '.env', content: envContent }
  ];

  // 3. Upload (Sequential with delay to avoid rate limits)
  for (const file of filesToUpload) {
    let sha: string | undefined;
    try {
      // List root to find file sha without 404ing on specific file
      const { data: existingFiles } = await octokit.repos.getContent({
        owner: user.login,
        repo: repoName,
        path: '',
      });
      
      if (Array.isArray(existingFiles)) {
        const existing = existingFiles.find((f: any) => f.name === file.name);
        if (existing) {
          sha = existing.sha;
        }
      }
    } catch (e: any) {
      // Ignore errors
    }

    await octokit.repos.createOrUpdateFileContents({
      owner: user.login,
      repo: repoName,
      path: file.name,
      message: `Update ${file.name}`,
      content: toBase64(file.content),
      sha,
    });
    
    // Small delay between uploads
    await delay(500);
  }
}
